OLED_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = no

ENCODER_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

EXTRAFLAGS += -flto
# DEBOUNCE_TYPE = asym_eager_defer_pk

